# {{templateWarning}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nxiq-operator-certified
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nxiq-operator-certified
  template:
    metadata:
      labels:
        name: nxiq-operator-certified
    spec:
      serviceAccountName: nxiq-operator-certified
      containers:
        - name: nxiq-operator-certified
          # Replace this with the built image name
          image: registry.connect.redhat.com/sonatype/nxiq-operator-certified:{{operatorVersion}}
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "nxiq-operator-certified"
            - name: RELATED_IMAGE_IQ
              value: registry.connect.redhat.com/sonatype/nexus-iq-server:{{certAppVersion}}
