# {{templateWarning}}
---
apiVersion: sonatype.com/v1alpha1
kind: NexusIQ
metadata:
  name: example-nexusiq
spec:
  # Default values copied from <project_dir>/helm-charts/iqserver/values.yaml

  # initContainers:
  #   - name: an-init-container
  #     image: busybox:1.28
  #     command: ['sh', '-c', 'echo "initializing"']
  deployment:
    postStart:
      command: null
  deploymentStrategy:
    type: Recreate
  fullnameOverride: ""
  imagePullSecrets: []
  ingress:
    annotations: {}
    enabled: false
    hosts: []
    path: /
    tls: []
  iq:
    adminPort: 8071
    applicationPort: 8070
    env:
      - name: JAVA_OPTS
        value: "-Djava.util.prefs.userRoot=$(SONATYPE_WORK)/javaprefs"
    configYaml:
      sonatypeWork: /sonatype-work
      createSampleData: true
      server:
        applicationConnectors:
          - port: 8070
            type: http
        adminConnectors:
          - port: 8071
            type: http
        requestLog:
          appenders:
            - type: file
              currentLogFilename: /var/log/nexus-iq-server/request.log
              logFormat: "%clientHost %l %user [%date] \"%requestURL\" %statusCode %bytesSent %elapsedTime \"%header{User-Agent}\""
              archivedLogFilenamePattern: /var/log/nexus-iq-server/request-%d.log.gz
              archivedFileCount: 50
      logging:
        level: DEBUG
        loggers:
          "com.sonatype.insight.scan": INFO
          "eu.medsea.mimeutil.MimeUtil2": INFO
          "org.apache.http": INFO
          "org.apache.http.wire": ERROR
          "org.eclipse.birt.report.engine.layout.pdf.font.FontConfigReader": WARN
          "org.eclipse.jetty": INFO
          "org.apache.shiro.web.filter.authc.BasicHttpAuthenticationFilter": INFO
          "com.sonatype.insight.audit":
            appenders:
              - type: file
                currentLogFilename: /var/log/nexus-iq-server/audit.log
                archivedLogFilenamePattern: /var/log/nexus-iq-server/audit-%d.log.gz
                archivedFileCount: 50
          "com.sonatype.insight.policy.violation":
            appenders:
              - type: console
                threshold: INFO
        appenders:
          - type: console
            threshold: INFO
            logFormat: "%d{'yyyy-MM-dd HH:mm:ss,SSSZ'} %level [%thread] %X{username} %logger - %msg%n"
          - type: file
            threshold: ALL
            logFormat: "%d{'yyyy-MM-dd HH:mm:ss,SSSZ'} %level [%thread] %X{username} %logger - %msg%n"
            currentLogFilename: /var/log/nexus-iq-server/clm-server.log
            archivedLogFilenamePattern: /var/log/nexus-iq-server/clm-server-%d.log.gz
            archivedFileCount: 50
    imageName: {{certAppSHA}}
    imagePullPolicy: IfNotPresent
    imagePullSecret: ""
    licenseSecret: ""
    memory: 1Gi
    name: nxiq
  nameOverride: ""
  persistence:
    accessMode: ReadWriteOnce
    storageSize: 1Gi
  service:
    annotations: {}
    enabled: false
    labels: {}
    ports:
      - name: nexus-service
        port: 80
        targetPort: 80
  serviceAccount:
    create: true
    name: null
