# {{templateWarning}}
apiVersion: sonatype.com/v1alpha1
kind: NexusIQ
metadata:
  name: example-nexusiq
spec:
  # Default values copied from <project_dir>/helm-charts/iqserver/values.yaml
  
  deployment:
    postStart:
      command: null
    preStart:
      command: null
  fullnameOverride: ""
  imagePullSecrets: []
  ingress:
    annotations: {}
    enabled: false
    hosts: []
    path: /
    tls: []
  iq:
    adminPort: 8071
    applicationPort: 8070
    configYaml:
      createSampleData: true
      server:
        adminConnectors:
        - port: 8071
          type: http
        applicationConnectors:
        - port: 8070
          type: http
      sonatypeWork: /sonatype-work
      requestLog:
        appenders:
          #All appenders set to console
          - type: file
            currentLogFilename: /var/log/nexus-iq-server/request.log
            # Do not display log statements below this threshold to stdout.
            # threshold: INFO
            logFormat: "%clientHost %l %user [%date] \"%requestURL\" %statusCode %bytesSent %elapsedTime \"%header{User-Agent}\""
            archivedLogFilenamePattern: /var/log/nexus-iq-server/request-%d.log.gz
            archivedFileCount: 50
    logging:
      # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
      level: DEBUG
      # Logger-specific settings.
      loggers:
        "com.sonatype.insight.scan": INFO
        "eu.medsea.mimeutil.MimeUtil2": INFO
        "org.apache.http": INFO
        "org.apache.http.wire": ERROR
        "org.eclipse.birt.report.engine.layout.pdf.font.FontConfigReader": WARN
        "org.eclipse.jetty": INFO
        "org.apache.shiro.web.filter.authc.BasicHttpAuthenticationFilter": INFO # WARNING: This reveals credentials at DEBUG level
        "com.sonatype.insight.audit":
          appenders:
            #All appenders set to console
            - type: file
              currentLogFilename: /var/log/nexus-iq-server/audit.log
              # Do not display log statements below this threshold to stdout.
              # threshold: INFO
              archivedLogFilenamePattern: /var/log/nexus-iq-server/audit-%d.log.gz
              archivedFileCount: 50
        "com.sonatype.insight.policy.violation":
          appenders:
            - type: console
              # Do not display log statements below this threshold to stdout.
              threshold: INFO
      appenders:
        # Settings for logging to stdout.
        - type: console
          # Do not display log statements below this threshold to stdout.
          threshold: INFO
          logFormat: "%d{'yyyy-MM-dd HH:mm:ss,SSSZ'} %level [%thread] %X{username} %logger - %msg%n"
        - type: file
          # Do not display log statements below this threshold to stdout.
          threshold: ALL
          logFormat: "%d{'yyyy-MM-dd HH:mm:ss,SSSZ'} %level [%thread] %X{username} %logger - %msg%n"
          # The file to which current statements will be logged.
          currentLogFilename: /var/log/nexus-iq-server/clm-server.log
          archivedLogFilenamePattern: /var/log/nexus-iq-server/clm-server-%d.log.gz
          archivedFileCount: 50
    imageName: registry.connect.redhat.com/sonatype/nexus-iq-server:{{certAppVersion}}
    imagePullPolicy: IfNotPresent
    imagePullSecret: ""
    licenseSecret: ""
    memory: 1Gi
    name: nxiq
  nameOverride: ""
  persistence:
    accessMode: ReadWriteOnce
    storageSize: 1Gi
  service:
    annotations: {}
    enabled: false
    labels: {}
    ports:
    - name: nexus-service
      port: 80
      targetPort: 80
  serviceAccount:
    create: true
    name: null
  
