apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nexusiqs.apm.nxiq.com
spec:
  group: apm.nxiq.com
  names:
    kind: NexusIQ
    listKind: NexusIQList
    plural: nexusiqs
    singular: nexusiq
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
