---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "iqserver.fullname" . }}
data:
  config.yml: |
{{ toYaml .Values.iq.configYaml | indent 4 }}

{{ if .Values.iq.certificates }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "iqserver.fullname" . }}-certificates
data:
{{ toYaml .Values.iq.certificates | indent 2 }}
{{- end }}
