{{- if .Values.iq.imagePullSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "iqserver.fullname" . }}-imagepull
data:
  .dockerconfigjson: {{ .Values.iq.imagePullSecret }}

type: kubernetes.io/dockerconfigjson
{{- end }}