kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "iqserver.fullname" . }}-data
  labels:
  {{- if .Values.persistence.annotations }}
annotations:
  {{ toYaml .Values.persistence.annotations | indent 4 }}
  {{- end }}
spec:
  {{- if .Values.persistence.storageClass }}
  {{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
  {{- end }}
  {{- end }}
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.storageSize | quote }}
